title: Tait Media Solutions

tagline: Digital Marketing Agency

logo: icon.png

description: |
  Tait Media Solutions specializes in helping the creators and businesses of tomorrow build a lasting brand.

url: https://taitmediasolutions.github.io

baseurl:

sass:
  sass_dir: _sass

navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Brands
  url: /brands/
- text: Contact
  url: /contact/
- text: Services
  url: /services/


author_name: "Anrich Tait"
author_bio: "Anrich Tait is the founder and creative director of Tait Media Solutions, where he helps brands grow through bold strategy and compelling media. When he's not collaborating with clients, he's either spending time with his family, refining his personal brand, or building one of his many passion-driven ventures."
author_url: "https://www.instagram.com/mister.tait/"
Author_location: "South Africa"
author_image: authorimage.jpg

facebook_username: "username"
instagram_username: "taitmediasolutions"
youtube_username: "taitmediasolutions"
linkedin_username: "tait-media-solutions"

paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
